name: Docker
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 45
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Add exec permission to docker.sh
      run: chmod +x ./.github/workflows/docker.sh

    - name: Build and push Docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: glitchd-ecr-repository-${{ secrets.STAGE }}-geth
      run: ./.github/workflows/docker.sh
