name: Docker
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    timeout-minutes: 45
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to ghcr.io
      env:
        PAT: ${{ secrets.GH_TOKEN }}
      run: printf "$PAT" | docker login --username _ --password-stdin ghcr.io

    - name: Build and push Docker images
      run: ./.github/workflows/docker.sh
